### ISSUE TITLE
repo name

### ISSUE THREAD

**Issue by iddq** [rrothwell/retro-hd6302-sbc-barta#1]
Hi, Is it 6302?

**Comment by rrothwell** [comment]
Thanks, It should be 6303. It’s just a typo.Sent from my iPhoneOn 21 Jan 2023, at 4:17 am, Gabor ***@***.***> wrote:﻿
Hi, Is it 6302?

**Comment by iddq** [comment]
Can you please change it to 6303?

**Comment by rrothwell** [comment]
I could try, but last time I had to fix a typo in a repo name it’s was not easy. I’ll check to see if things have improved.Sent from my iPhoneOn 29 Jan 2023, at 11:53 pm, Gabor ***@***.***> wrote:﻿
Can you please change it to 6303?

**Comment by iddq** [comment]
Rename is the first option on settings page

**Comment by rrothwell** [comment]
Hi, I’ve updated the repo name as you requested.Sent from my iPhoneOn 1 Feb 2023, at 8:07 pm, Gabor ***@***.***> wrote:﻿
Rename is the first option on settings page

**Comment by iddq** [comment]
thanks
